# mmm_dbt_project/models/staging/schema.yml

version: 2

sources:
  - name: seeds
    schema: main_raw
    tables:
      - name: raw_facebook_spend
      - name: raw_google_spend
      - name: raw_tiktok_spend
      - name: raw_crm_sales
      - name: raw_control_variables

models:
  - name: stg_facebook_spend
    columns:
      - name: date
        tests:
          - not_null
          - unique
      - name: spend
        tests:
          - not_null
          - expect_column_values_to_be_positive # Calling your custom test

  - name: stg_google_spend
    columns:
      - name: date
        tests:
          - not_null
          - unique
      - name: spend 
        tests:
          - not_null
          - expect_column_values_to_be_positive # Calling your custom test

  - name: stg_crm_sales
    columns:
      - name: date
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
          - expect_column_values_to_be_positive # Calling your custom test

  - name: mmm_aggregated_data
    columns:
      - name: date
        tests:
          - unique
          - not_null